import AddPetForm from "@/Components/App/All-Pate/AddPetForm";

export const metadata = {
  title: "PetHub | Add Pate page",
  description: "Generated by create next app",
};

const AddPatePage = () => {
  return (
    <div>
      <AddPetForm />
    </div>
  );
};

export default AddPatePage;
