import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProveider from "@/Components/NextProveider/ThemeProveider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PetHub | Home Page",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col bg-background text-foreground"
        wotdisconnected="true"
      >
        <ThemeProveider>
          <main>{children}</main>
          <Toaster />
        </ThemeProveider>
      </body>
    </html>
  );
}
