import MyListingPage from "@/Components/App/MyListing/MyListingPage";
export const metadata = {
  title: "PetHub | My Listing Page",
  description: "Generated by create next app",
};

const MyListings = () => {
  return (
    <div>
      <MyListingPage />
    </div>
  );
};

export default MyListings;
